### ISSUE TITLE
Driver not added to universal-resolver

### ISSUE THREAD

**Issue by podefr** [Meeco/hedera-did-universal-resolver-driver#3]
Hi team,

I've added this driver to the universal resolver's default [docker-compose.yml](https://github.com/decentralized-identity/universal-resolver/blob/main/docker-compose.yml), so the resulting file looks like this:

```
version: "3.6"

networks:
  default:
    name: universal-resolver

services:
  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8080:8080"
  driver-did-btcr:
    image: universalresolver/driver-did-btcr:latest
    environment:
      uniresolver_driver_did_btcr_bitcoinConnection: ${uniresolver_driver_did_btcr_bitcoinConnection}
      uniresolver_driver_did_btcr_rpcUrlMainnet: ${uniresolver_driver_did_btcr_rpcUrlMainnet}
      uniresolver_driver_did_btcr_rpcUrlTestnet: ${uniresolver_driver_did_btcr_rpcUrlTestnet}
      uniresolver_driver_did_btcr_rpcCertMainnet: ${uniresolver_driver_did_btcr_rpcCertMainnet}
      uniresolver_driver_did_btcr_rpcCertTestnet: ${uniresolver_driver_did_btcr_rpcCertTestnet}
    ports:
      - "8081:8080"
  ...
  driver-did-hedera:
    image: meeco/uni-resolver-driver-did-hedera:latest
    ports:
      - "8145:8081"
    environment:
      OPERATOR_ID: ${HEDERA_DRIVER_OPERATOR_ID}
      OPERATOR_KEY: ${HEDERA_DRIVER_OPERATOR_KEY}
```

I added the 2 env variables to my `.env` and I verified that they were available to the node process.

I'm able to call the resolver when calling the container directly but not through the universal resolver itself:

This works:

```
curl -X GET http://localhost:8145/1.0/identifiers/did:hedera:testnet:z5P1atRTktJL8Ap7saabU4pHEaT96ZBFHQU5qeYjxYLqr_0.0.15424549
{"didDocumentMetadata":{"versionId":null},"didResolutionMetadata":{"contentType":"application/did+ld+json"},"didDocument":{"@context":"https://www.w3.org/ns/did/v1","id":"did:hedera:testnet:z5P1atRTktJL8Ap7saabU4pHEaT96ZBFHQU5qeYjxYLqr_0.0.15424549","verificationMethod":[],"assertionMethod":[],"authentication":[]}}
```

This doesn't:

```
curl -X GET http://localhost:8080/1.0/identifiers/did:hedera:testnet:z5P1atRTktJL8Ap7saabU4pHEaT96ZBFHQU5qeYjxYLqr_0.0.15424549

{"@context":"https://w3id.org/did-resolution/v1","didDocument":null,"didResolutionMetadata":{"error":"methodNotSupported","errorMessage":"Method not supported: hedera","contentType":"application/did+ld+json"},"didDocumentMetadata":{}}
```

Note that the resolver is not listed in the list of methods:

```
curl -X GET http://localhost:8080/1.0/methods/ 
     
["btcr","sov","indy","v1","stack","web","ethr","ens","peer","eosio","nacl","jolo","hcr","elem","github","ccp","ont","kilt","factom","io","bba","schema","ion","ace","gatc","icon","vaa","unisot","sol","lit","ebsi","emtrust","meta","tz","key","pkh","orb","oyd","moncon","dock","mydata","dns","everscale","ala","cheqd","com","dyne","jwk","kscirc","iscc","ev","iid","evan","bid","algo","polygonid","pdc","tys","plc"]
```

Should `hedera` be listed in the `methods` response and if so, am I missing something in the configuration so that the driver gets properly detected?

Thanks!

**Comment by vijayshiyani** [comment]
@podefr 

It appears that the Hedera DID pattern matching is absent in your application.yml file.
```
    - pattern: "^(did:hedera:.+)$"
      url: http://driver-did-hedera:8081/
      testIdentifiers:
        - did:hedera:testnet:z5P1atRTktJL8Ap7saabU4pHEaT96ZBFHQU5qeYjxYLqr_0.0.15424549
        - did:hedera:testnet:G4YcoGJtgbNNYWvBknZz52f3pKRZamSJwFv9AGRQYaH1_0.0.500550
      
```

Additionally, you will need to locally rebuild uni-resolver-web to enable the Hedera method in the following curl command: 

```
curl -X GET http://localhost:8080/1.0/methods/
```
command to rebuild uni-resolver-web
```
docker build -f ./uni-resolver-web/docker/Dockerfile . -t universalresolver/uni-resolver-web
```

To facilitate testing the driver locally, you can refer to this guide: [link to guide](https://github.com/Meeco/universal-resolver/blob/62d2e8847458cf8ba7f416127d6f79174f473bab/docs/driver-development.md#how-to-test-a-driver-locally-with-the-universal-resolver).

Furthermore, I have updated the Meeco fork of the [universal-resolver](https://github.com/Meeco/universal-resolver), and committed the necessary changes for the universal-resolver on the [feature/add-did-hedera branch](https://github.com/Meeco/universal-resolver/tree/feature/add-did-hedera), which you can review at: [link to commit](https://github.com/Meeco/universal-resolver/commit/0d674242fda4915cbb8c7f14e6b6cd4e69e4c053).

Please note that I have made modifications, including switching to eclipse-temurin:17-jre-alpine to 17-jre-jammy as the Docker image is unavailable for my ARM64 platform.

in addition,  you don't need OPERATOR_ID &  OPERATOR_KEY to resolve a DID. 

I hope this help.
